version: "3"
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .:/application
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./mysqlconf:/etc/mysql/conf.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=PlantZo@123
      - MYSQL_DATABASE=koja
  koja-flask:
    container_name: koja-flask
    build: .
    ports:
      - "80:5000"
    volumes:
      - ./:/app
    environment:
      FLASK_ENV: development
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
  redis:
    image: redis
    container_name: koja-redis
    restart: always
    ports:
      - "6379:6379"
