version: "3"
services:
  koja-flask:
    container_name: koja-flask
    build: .
    ports:
      - "80:5000"
    volumes:
      - ./:/app
    environment:
      FLASK_ENV: development
    restart: always