version: "3"
services:
  koja:
    container_name: koja
    build: .
    ports:
      - "80:5000"
    volumes:
      - ./:/app
    environment:
      FLASK_ENV: development
    restart: always
    networks:
      - python-network

networks:
  python-network:
    driver: bridge
